// Code generated by rice embed-go; DO NOT EDIT.
package main

import (
	"time"

	"github.com/GeertJohan/go.rice/embedded"
)

func init() {

	// define files
	file2 := &embedded.EmbeddedFile{
		Filename:    "app.css",
		FileModTime: time.Unix(1591023400, 0),

		Content: string("* {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n    font-family: \"Inter\";\n    color: #F5F5F5;\n    font-size: 13.5px;\n}\n\nbody {\n    height: 100vh;\n    width: 100vw;\n    background-color: #FFF;\n    display: flex;\n    flex-direction: column;\n    justify-content: center;\n    align-items: center;\n}\n\nh1 {\n    font-weight: 600;\n    margin-bottom: 10px;\n    color: #202125;\n}\n\n.links-wrapper {\n    display: flex;\n}\n\n.links-wrapper div {\n    display: flex;\n    flex-direction: column;\n    margin-right: 110px;\n}\n\n.links-wrapper div:last-child {\n    margin-right: 0;\n}\n\n.links-wrapper div a {\n    text-decoration: none;\n    color: #202125;\n    opacity: 0.5;\n    margin-bottom: 8px;\n}"),
	}
	file3 := &embedded.EmbeddedFile{
		Filename:    "app.js",
		FileModTime: time.Unix(1591009675, 0),

		Content: string("window.addEventListener('load', () => {\n    //document.querySelector('body').innerHTML = \"Hello from duree\"\n});"),
	}

	// define dirs
	dir1 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1591004456, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file2, // "app.css"
			file3, // "app.js"

		},
	}

	// link ChildDirs
	dir1.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`static`, &embedded.EmbeddedBox{
		Name: `static`,
		Time: time.Unix(1591004456, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir1,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"app.css": file2,
			"app.js":  file3,
		},
	})
}

func init() {

	// define files
	file5 := &embedded.EmbeddedFile{
		Filename:    "index.html",
		FileModTime: time.Unix(1591023554, 0),

		Content: string("<!DOCTYPE html>\n<html lang=\"en\">\n\n    <head>\n        <meta charset=\"UTF-8\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n        <title>duree</title>\n        <link rel=\"stylesheet\" href=\"/static/app.css\">\n    </head>\n\n    <body>\n\n        <div class=\"links-wrapper\">\n            {{range .}}\n                <div class=\"{{.Group}}-links\">\n                    <h1>{{.Group}}</h1>\n                    {{range .Items}}\n                        <a href=\"{{.URL}}\">{{.Title}}</a>\n                    {{end}} \n                </div>\n            {{end}}\n        </div>\n\n        <script async src=\"/static/app.js\"></script>\n    </body>\n\n</html>"),
	}

	// define dirs
	dir4 := &embedded.EmbeddedDir{
		Filename:   "",
		DirModTime: time.Unix(1589918547, 0),
		ChildFiles: []*embedded.EmbeddedFile{
			file5, // "index.html"

		},
	}

	// link ChildDirs
	dir4.ChildDirs = []*embedded.EmbeddedDir{}

	// register embeddedBox
	embedded.RegisterEmbeddedBox(`templates`, &embedded.EmbeddedBox{
		Name: `templates`,
		Time: time.Unix(1589918547, 0),
		Dirs: map[string]*embedded.EmbeddedDir{
			"": dir4,
		},
		Files: map[string]*embedded.EmbeddedFile{
			"index.html": file5,
		},
	})
}
